data_file: "datasets/mouse_stroke.h5"
outdir: "./outputs"
stage: "train"
batch_size: "auto"
encoder_layers: [256, 64]
decoder_layers: [64, 256]
GP_dim: 2
Normal_dim: 8
lr: 0.0002
maxiter: 3000
patience: 200
project_index: "patch"
pert_cells: "../pert_cells/pert_cells_stroke_sham1_CIA.txt"
model_file: "model_stroke2d.pt"
pert_batch: "Sham1"
target_cell_perturbation: "ICA"
pert_cell_number: 40
project_index: "stroke_2D"
wandb: true
wandb_project: "concert"
wandb_run: "test"
wandb_mode: "online"

